version: '3.8'

services:
  # Serveur RTMP avec NGINX
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx_rtmp
    ports:
      - "1935:1935"     # Port RTMP pour la diffusion en direct
      - "8080:8080"     # Port HTTP pour accéder au dashboard RTMP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Fichier de configuration RTMP

  # Serveur Icecast pour la diffusion
  icecast:
    image: mdns/icecast
    container_name: icecast
    restart: always
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
      - ICECAST_ADMIN_PASSWORD=adminpassword
      - ICECAST_PASSWORD=hackme
    ports:
      - "8000:8000"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml  # Fichier de configuration Icecast

  # FFmpeg pour capturer le flux WebSDR et l'envoyer au serveur RTMP
  ffmpeg-websdr:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg_websdr
    restart: always
    command: >
      ffmpeg -i http://websdr.78dx.ru:8901/?tune=145736usb
      -c:a aac -b:a 128k -f flv rtmp://nginx_rtmp/live/stream

  # FFmpeg pour capturer le flux RTMP et l'envoyer vers Icecast
  ffmpeg-to-icecast:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg_to_icecast
    restart: always
    depends_on:
      - nginx-rtmp
      - icecast
    command: >
      ffmpeg -i rtmp://nginx_rtmp/live/stream
      -c:a libmp3lame -b:a 128k -f mp3 icecast://source:hackme@icecast:8000/stream
